/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;

import data.MovimientoDAL;
import security.Login;

/**
 *
 * @author Piero
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    private Login authenticado = null;

    public main(Login authenticado) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.authenticado = authenticado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        MOperaciones = new javax.swing.JMenu();
        IRetirar = new javax.swing.JMenuItem();
        ITransferir = new javax.swing.JMenuItem();
        MVer = new javax.swing.JMenu();
        iDetalleCuenta = new javax.swing.JMenuItem();
        IUltimosMovimiento = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MOperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/settings_icon_150742.png"))); // NOI18N
        MOperaciones.setText("OPERACIONES");

        IRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/coins_money_bank_currency_dollar_icon_150733.png"))); // NOI18N
        IRetirar.setText("RETIRAR");
        IRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IRetirarActionPerformed(evt);
            }
        });
        MOperaciones.add(IRetirar);

        ITransferir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/money_currency_change_dollar_coins_business_icon_150706.png"))); // NOI18N
        ITransferir.setText("TRANSFERIR");
        ITransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITransferirActionPerformed(evt);
            }
        });
        MOperaciones.add(ITransferir);

        jMenuBar1.add(MOperaciones);

        MVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search_find_locate_money_dollar_coin_currency_business_icon_150704.png"))); // NOI18N
        MVer.setText("VER");

        iDetalleCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/invoice_dollar_business_document_dollar_coin_icon_150738.png"))); // NOI18N
        iDetalleCuenta.setText("DETALLE DE CUENTA");
        iDetalleCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iDetalleCuentaActionPerformed(evt);
            }
        });
        MVer.add(iDetalleCuenta);

        IUltimosMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cloud_finance_business_branch_dollar_coin_currency_icon_150731.png"))); // NOI18N
        IUltimosMovimiento.setText("ULTIMOS MOVIMIENTOS");
        IUltimosMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IUltimosMovimientoActionPerformed(evt);
            }
        });
        MVer.add(IUltimosMovimiento);

        jMenuBar1.add(MVer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IRetirarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_IRetirarActionPerformed
        // TODO add your handling code here:
        retirar abrir = new retirar(authenticado);
        abrir.setVisible(true);
    }// GEN-LAST:event_IRetirarActionPerformed

    private void iDetalleCuentaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_IUltimosMActionPerformed
        // TODO add your handling code here:
        Login cuenta = MovimientoDAL.getCuenta(authenticado.getCuenta().getCodigo());

        JOptionPane.showMessageDialog(null,
                "Titular de La cuenta : " + cuenta.getCliente().getApellidoPaterno()
                + " " + cuenta.getCliente().getApellidoMaterno() + " " + cuenta.getCliente().getNombre()
                + "\n" + "Tipo de Moneda : " + cuenta.getCuenta().getMoneda().getDescripcion()
                + "\n" + "Saldo Actual : " + cuenta.getCuenta().getSaldo(),
                 "DETALLE DE CUENTA", 1);

    }// GEN-LAST:event_IUltimosMActionPerformed

    private void IUltimosMovimientoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        String mensaje = MovimientoDAL.getMovimientos(authenticado.getCuenta().getCodigo());
        JOptionPane.showMessageDialog(null, mensaje, "ULTIMOS MOVIMIENTOS", 1);
    }// GEN-LAST:event_jMenuItem5ActionPerformed

    private void ITransferirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ITransferirActionPerformed
        // TODO add your handling code here:
        transferir abrir = new transferir(authenticado);
        abrir.setVisible(true);
    }// GEN-LAST:event_ITransferirActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    // /* Set the Nimbus look and feel */
    // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
    // default look and feel.
    // * For details see
    // http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    // */
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // }
    // //</editor-fold>
    //
    // /* Create and display the form */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // new main().setVisible(true);
    // }
    // });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem IRetirar;
    private javax.swing.JMenuItem ITransferir;
    private javax.swing.JMenuItem IUltimosMovimiento;
    private javax.swing.JMenu MOperaciones;
    private javax.swing.JMenu MVer;
    private javax.swing.JMenuItem iDetalleCuenta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
